version: '3'
services:

  app:
    build: .
    container_name: tnm-app
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    security_opt:
      - apparmor:unconfined
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tnm
    ports:
      - "5432:5432"
    volumes:
      - PostgreSQL:/var/lib/postgresql/data

volumes:
  PostgreSQL:

networks:
  app-network:
    driver: bridge
